### ISSUE TITLE
QCAR/Matrices.h not found

### ISSUE THREAD

**Issue by kweles** [csotiriou/vuforia-video-streaming#1]
Helo! 
I found your code and i want to test it, however i am receiving this error QCAR/Matrices.h not found.

What can i do to solve this problem!

Thanks!

**Comment by csotiriou** [comment]
You need to download the Vuforia library and include it into the project. I am not distributing the vuforia Library along with the source, because this would be illegal.

**Comment by kweles** [comment]
Ok, Thanks! I understood.
I tried put the vuforia-sdk-ios-5-5-9, but in this version there is no QCAR. What's sdk version do you use? Where are i can download it?

Sorry for importunate you!

Thanks for you attention!

**Comment by kweles** [comment]
Hi Thanks for reply!
I can't find vuforia sdk 4.  The new sdk 5 can't play with your code. I appreciate some help where find the sdk 4.

Thanks.
